### ISSUE TITLE
all p5 shows are broken

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/rapidriteros#9]
```
json_payload {'p5': 'let h=0;\r\n\r\nfunction setup() {\r\n  background(255);\r\n  fill(0);\r\n}\r\n\r\nfunction draw() {\r\n  background(255);\r\n  angleMode(DEGREES);\r\n  h = abs(sin(frameCount));\r\n  noStroke();\r\n  ellipse(width/4,height/2, width/10, width/10);\r\n  ellipse(3 * width/4, height/2, width/10, width/10);\r\n  stroke(0);\r\n  strokeCap(SQUARE);\r\n  strokeWeight(3);\r\n  strokeJoin(BEVEL);\r\n  beginShape();\r\n  vertex(width/2 - width/10, height/2 + height/12);\r\n  quadraticVertex(width/2, height/2+height/12+(11*h), width/2 + width/10, height/2 + height/12);\r\n  endShape(CLOSE);\r\n}'}
 (node:244) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
 (Use `node --trace-deprecation ...` to show where the warning was created)
 /app/subrenderer/node_modules/window/node_modules/jsdom/lib/jsdom/living/generated/Event.js:286
     throw new TypeError(`${context} is not of type 'Event'.`);
           ^
 
 TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
     at convert (/app/subrenderer/node_modules/window/node_modules/jsdom/lib/jsdom/living/generated/Event.js:286:11)
     at Window.dispatchEvent (/app/subrenderer/node_modules/window/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:141:16)
     at /app/subrenderer/node_modules/p5/lib/p5.min.js:2:455373
     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
 
 Node.js v22.11.0
```

**Comment by gregsadetsky** [comment]
something changed?? jsdom??

**Comment by gregsadetsky** [comment]
they're fixed!! somehow - mostly thanks to [this comment](https://github.com/jsdom/jsdom/issues/3331#issuecomment-1137376839)!

so many p5 sketches!!!!!!!!!

<img width="554" alt="image" src="https://github.com/user-attachments/assets/f7383797-74aa-4e58-9e33-a345cb73f603">

<img width="499" alt="image" src="https://github.com/user-attachments/assets/fada3594-3474-4f01-8d41-50b0e6bb6cef">

<img width="529" alt="image" src="https://github.com/user-attachments/assets/1919c606-5e37-4c85-a542-0e3fabd49b22">
